per_gpu_train_batch_size : 128 # 128 exeeds GPU memory
per_gpu_eval_batch_size : 128 # not used in CLIP training
n_gpu : 4
num_workers : 4 # number of workers for data loading
num_train_epochs : 100 # number of epochs to train

name : 'Training-Lateral-MultiPrompt-New' # name of the experiment
save_steps_epochs : 10
dataset : 'csv/train_short_lateral_clean.csv' # dataset to train on

gradient_accumulation_steps : 1 # Number of updates steps to accumulate before backward

logging_steps : 100 #  log every this steps
save_steps : 0 # 1000 steps take 1 hour with 4 GTX1080 GPUs and batch size = 256 (64 per GPU)

saved_checkpoints : '../../../snic2022-5-277/dmolino/CXR_Training/saved_checkpoints/Lateral' # path1 to save checkpoints
logs : 'CXR_Training/logs' # path1 to save logs

clip_weights : 'Clip_Training/saved_checkpoints/Training_Clip_5e^-5/checkpoint_29_epoch_Training_Clip_5e^-5.pt'

optimizer:
  params:
    eps: 1.0e-08
    lr: 5e-5
    weight_decay: 1e-4
  type: AdamW

multi_prompt : True
view: 'lateral'
